server:
  port: 9527
  
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PROVIDER-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/ok/**
        - id: payment_routh2
          uri: lb://CLOUD-PROVIDER-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-27T17:08:18.723+08:00[Asia/Shanghai]
            - Cookie=username,th
    
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    